/**
 * Post-build: write `dist/sitemap.xml`, `dist/_redirects`, and `dist/.htaccess`.
 *
 * Sitemap: sole source of truth — do not add `public/sitemap.xml`. Astro copies `public/`
 * during build, then this script overwrites `dist/sitemap.xml`.
 *
 * Redirects: one rule list → Netlify/Cloudflare `_redirects` + Apache `.htaccess` (Plesk).
 * `src/pages/index.astro` and legacy Astro routes keep client/meta fallbacks for dev/preview.
 *
 * Locales: `src/i18n/config.ts` → `supportedLanguages`.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { supportedLanguages } from "../src/i18n/config";

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = join(__dirname, "..", "dist");

const SITE = "https://cheqsplitapp.com";

/** Path-only redirect (leading slash, optional trailing slash on `from`). */
type RedirectRule = { from: string; to: string };

function buildRedirectRules(): RedirectRule[] {
  return [
    { from: "/", to: "/en/" },
    { from: "/split-bill-app", to: "/en/split-bill-app/" },
    { from: "/split-bill-app/", to: "/en/split-bill-app/" },
    ...supportedLanguages.map((lang) => ({
      from: `/${lang}`,
      to: `/${lang}/`,
    })),
    ...supportedLanguages.map((lang) => ({
      from: `/${lang}/split-bill-app`,
      to: `/${lang}/split-bill-app/`,
    })),
    ...supportedLanguages.map((lang) => ({
      from: `/${lang}/group-expense-tracker`,
      to: `/${lang}/group-expense-tracker/`,
    })),
    {
      from: "/group-expense-tracker",
      to: "/en/group-expense-tracker/",
    },
    ...supportedLanguages.map((lang) => ({
      from: `/${lang}/guides/how-to-split-a-restaurant-bill`,
      to: `/${lang}/guides/how-to-split-a-restaurant-bill/`,
    })),
    {
      from: "/guides/how-to-split-a-restaurant-bill",
      to: "/en/guides/how-to-split-a-restaurant-bill/",
    },
    ...supportedLanguages.map((lang) => ({
      from: `/${lang}/guides/how-to-split-trip-expenses`,
      to: `/${lang}/guides/how-to-split-trip-expenses/`,
    })),
    {
      from: "/guides/how-to-split-trip-expenses",
      to: "/en/guides/how-to-split-trip-expenses/",
    },
    ...supportedLanguages.map((lang) => ({
      from: `/${lang}/guides`,
      to: `/${lang}/guides/`,
    })),
    { from: "/guides", to: "/en/guides/" },
    { from: "/privacy-policy", to: "/en/privacy-policy/" },
    { from: "/terms-of-service", to: "/en/terms-of-service/" },
    { from: "/delete-account", to: "/en/delete-account/" },
    { from: "/delete-data", to: "/en/delete-data/" },
    { from: "/support", to: "/en/support/" },
  ];
}

function formatNetlifyRedirects(rules: RedirectRule[]): string {
  return [
    "# Generated by scripts/generate-sitemap.ts — Netlify / Cloudflare Pages `_redirects`",
    ...rules.map(({ from, to }) => `${from} ${to} 301`),
  ].join("\n");
}

function escapeRegex(segment: string): string {
  return segment.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/** Exact path → Apache RewriteRule pattern (no leading slash in pattern). */
function pathToRewritePattern(from: string): string {
  if (from === "/" || from === "") return "^$";
  const trailing = from.endsWith("/") && from.length > 1;
  const core = trailing ? from.slice(1, -1) : from.slice(1);
  const escaped = core.split("/").map(escapeRegex).join("/");
  return trailing ? `^${escaped}/$` : `^${escaped}$`;
}

function formatApacheHtaccess(rules: RedirectRule[]): string {
  const lines = [
    "# Generated by scripts/generate-sitemap.ts — Apache mod_rewrite (Plesk/HOST.MD httpdocs)",
    "# Path redirects only. HTTPS and preferred-host redirects are handled by Plesk.",
    "RewriteEngine On",
    "",
    ...rules.map(
      ({ from, to }) =>
        `RewriteRule ${pathToRewritePattern(from)} ${to} [R=301,L,QSA]`,
    ),
  ];
  return `${lines.join("\n")}\n`;
}

const homeUrls = supportedLanguages.map(
  (lang) => `  <url><loc>${SITE}/${lang}/</loc><priority>1.0</priority></url>`,
);
const splitBillUrls = supportedLanguages.map(
  (lang) =>
    `  <url><loc>${SITE}/${lang}/split-bill-app/</loc><priority>0.85</priority></url>`,
);

const groupExpenseUrls = supportedLanguages.map(
  (lang) =>
    `  <url><loc>${SITE}/${lang}/group-expense-tracker/</loc><priority>0.85</priority></url>`,
);
const guidesHubUrls = supportedLanguages.map(
  (lang) =>
    `  <url><loc>${SITE}/${lang}/guides/</loc><priority>0.65</priority></url>`,
);
const restaurantGuideUrls = supportedLanguages.map(
  (lang) =>
    `  <url><loc>${SITE}/${lang}/guides/how-to-split-a-restaurant-bill/</loc><priority>0.7</priority></url>`,
);
const tripGuideUrls = supportedLanguages.map(
  (lang) =>
    `  <url><loc>${SITE}/${lang}/guides/how-to-split-trip-expenses/</loc><priority>0.7</priority></url>`,
);

const LEGAL_SLUGS = [
  "privacy-policy",
  "terms-of-service",
  "delete-account",
  "delete-data",
  "support",
] as const;
const legalPriority: Record<(typeof LEGAL_SLUGS)[number], string> = {
  "privacy-policy": "0.4",
  "terms-of-service": "0.4",
  "delete-account": "0.35",
  "delete-data": "0.35",
  support: "0.5",
};

const legalUrls = supportedLanguages.flatMap((lang) =>
  LEGAL_SLUGS.map(
    (slug) =>
      `  <url><loc>${SITE}/${lang}/${slug}/</loc><priority>${legalPriority[slug]}</priority></url>`,
  ),
);

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${[...homeUrls, ...splitBillUrls, ...groupExpenseUrls, ...guidesHubUrls, ...restaurantGuideUrls, ...tripGuideUrls, ...legalUrls].join("\n")}
</urlset>
`;

const redirectRules = buildRedirectRules();

writeFileSync(join(distDir, "sitemap.xml"), xml, "utf8");
writeFileSync(join(distDir, "_redirects"), `${formatNetlifyRedirects(redirectRules)}\n`, "utf8");
writeFileSync(join(distDir, ".htaccess"), formatApacheHtaccess(redirectRules), "utf8");

const n = supportedLanguages.length * 6 + legalUrls.length;
console.log(`[generate-sitemap] wrote dist/sitemap.xml (${n} URLs)`);
console.log(`[generate-sitemap] wrote dist/_redirects (${redirectRules.length} rules)`);
console.log(`[generate-sitemap] wrote dist/.htaccess (${redirectRules.length} rules)`);
