/**
 * Post-build: write `dist/sitemap.xml` and `dist/_redirects` (Netlify / Cloudflare Pages).
 * Locales are sourced from `src/i18n/config.ts` → `supportedLanguages`.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { supportedLanguages } from "../src/i18n/config";

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = join(__dirname, "..", "dist");

const SITE = "https://cheqsplitapp.com";

const homeUrls = supportedLanguages.map(
  (lang) => `  <url><loc>${SITE}/${lang}/</loc><priority>1.0</priority></url>`,
);
const splitBillUrls = supportedLanguages.map(
  (lang) =>
    `  <url><loc>${SITE}/${lang}/split-bill-app/</loc><priority>0.85</priority></url>`,
);

const legalUrls = [
  `  <url><loc>${SITE}/privacy-policy/</loc><priority>0.4</priority></url>`,
  `  <url><loc>${SITE}/terms-of-service/</loc><priority>0.4</priority></url>`,
  `  <url><loc>${SITE}/delete-account/</loc><priority>0.35</priority></url>`,
  `  <url><loc>${SITE}/delete-data/</loc><priority>0.35</priority></url>`,
  `  <url><loc>${SITE}/support/</loc><priority>0.5</priority></url>`,
];

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${[...homeUrls, ...splitBillUrls, ...legalUrls].join("\n")}
</urlset>
`;

const redirects = [
  "# Trailing slash enforcement (301). Generated by scripts/generate-sitemap.ts",
  ...supportedLanguages.map((lang) => `/${lang} /${lang}/ 301`),
  ...supportedLanguages.map(
    (lang) => `/${lang}/split-bill-app /${lang}/split-bill-app/ 301`,
  ),
  "/split-bill-app /split-bill-app/ 301",
  "/privacy-policy /privacy-policy/ 301",
  "/terms-of-service /terms-of-service/ 301",
  "/delete-account /delete-account/ 301",
  "/delete-data /delete-data/ 301",
  "/support /support/ 301",
].join("\n");

writeFileSync(join(distDir, "sitemap.xml"), xml, "utf8");
writeFileSync(join(distDir, "_redirects"), redirects + "\n", "utf8");

const n = supportedLanguages.length * 2 + legalUrls.length;
console.log(`[generate-sitemap] wrote dist/sitemap.xml (${n} URLs)`);
console.log(
  `[generate-sitemap] wrote dist/_redirects (${supportedLanguages.length * 2 + 6} rules)`,
);
