/**
 * Post-build: write `dist/sitemap.xml` and `dist/_redirects` (Netlify / Cloudflare Pages).
 * Locales are sourced from `src/i18n/config.ts` → `supportedLanguages`.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { supportedLanguages } from "../src/i18n/config";

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = join(__dirname, "..", "dist");

const SITE = "https://cheqsplitapp.com";

const homeUrls = supportedLanguages.map(
  (lang) => `  <url><loc>${SITE}/${lang}/</loc><priority>1.0</priority></url>`,
);
const splitBillUrls = supportedLanguages.map(
  (lang) =>
    `  <url><loc>${SITE}/${lang}/split-bill-app/</loc><priority>0.85</priority></url>`,
);

const LEGAL_SLUGS = [
  "privacy-policy",
  "terms-of-service",
  "delete-account",
  "delete-data",
  "support",
] as const;
const legalPriority: Record<(typeof LEGAL_SLUGS)[number], string> = {
  "privacy-policy": "0.4",
  "terms-of-service": "0.4",
  "delete-account": "0.35",
  "delete-data": "0.35",
  support: "0.5",
};

const legalUrls = supportedLanguages.flatMap((lang) =>
  LEGAL_SLUGS.map(
    (slug) =>
      `  <url><loc>${SITE}/${lang}/${slug}/</loc><priority>${legalPriority[slug]}</priority></url>`,
  ),
);

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${[...homeUrls, ...splitBillUrls, ...legalUrls].join("\n")}
</urlset>
`;

const redirects = [
  "# Trailing slash enforcement (301). Generated by scripts/generate-sitemap.ts",
  ...supportedLanguages.map((lang) => `/${lang} /${lang}/ 301`),
  ...supportedLanguages.map(
    (lang) => `/${lang}/split-bill-app /${lang}/split-bill-app/ 301`,
  ),
  "/split-bill-app /split-bill-app/ 301",
  "/privacy-policy /en/privacy-policy/ 301",
  "/terms-of-service /en/terms-of-service/ 301",
  "/delete-account /en/delete-account/ 301",
  "/delete-data /en/delete-data/ 301",
  "/support /en/support/ 301",
].join("\n");

writeFileSync(join(distDir, "sitemap.xml"), xml, "utf8");
writeFileSync(join(distDir, "_redirects"), redirects + "\n", "utf8");

const n = supportedLanguages.length * 2 + legalUrls.length;
console.log(`[generate-sitemap] wrote dist/sitemap.xml (${n} URLs)`);
const redirectRules =
  1 + supportedLanguages.length * 2 + 1 + LEGAL_SLUGS.length;
console.log(`[generate-sitemap] wrote dist/_redirects (${redirectRules} rules)`);
